// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlFvTX9dTSXoEfsa8PPCR5FgKAWki2YYI',
    appId: '1:688597490158:web:20834c5c8d411d924596ff',
    messagingSenderId: '688597490158',
    projectId: 'darc-example',
    authDomain: 'darc-example.firebaseapp.com',
    storageBucket: 'darc-example.firebasestorage.app',
    measurementId: 'G-ZDX05730R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdHDMhsHtJ5kDIpX8YyTl743WIN7t3Nng',
    appId: '1:688597490158:android:ac2a3b4220b406f84596ff',
    messagingSenderId: '688597490158',
    projectId: 'darc-example',
    storageBucket: 'darc-example.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVkF39kNrIDmh8u9ykMCBpYUqNkrLtl4Q',
    appId: '1:688597490158:ios:0ae66744393f54b04596ff',
    messagingSenderId: '688597490158',
    projectId: 'darc-example',
    storageBucket: 'darc-example.firebasestorage.app',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVkF39kNrIDmh8u9ykMCBpYUqNkrLtl4Q',
    appId: '1:688597490158:ios:0ae66744393f54b04596ff',
    messagingSenderId: '688597490158',
    projectId: 'darc-example',
    storageBucket: 'darc-example.firebasestorage.app',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlFvTX9dTSXoEfsa8PPCR5FgKAWki2YYI',
    appId: '1:688597490158:web:1b67508763e640374596ff',
    messagingSenderId: '688597490158',
    projectId: 'darc-example',
    authDomain: 'darc-example.firebaseapp.com',
    storageBucket: 'darc-example.firebasestorage.app',
    measurementId: 'G-WH7ETB8Y85',
  );
}
